%
%   Solução do Balanço de Ponta Determinístico
%

fprintf('Calculando balanço de ponta probabilístico...')
Sobra = zeros(nsis,nper,nsim);           % Inicializa a matriz de sobras
for iper = mesi:nper
   for isim = 1:nsim
      fprintf('   Período %2.2i, Série %4.4i',iper,isim );
      [Deficit(:,iper,isim), Excesso(:,iper,isim), ...
          Interc(:,:,iper,isim), GH(:,iper,isim), ...
          GT(:,iper,isim)] = ...
          resolveBP(nsis, nfic, GHmax(iper,:,isim),...
          GTmax(iper,:), DispNS(:,iper), Mercado(:,iper),...
          LimInterc(:,iper), GTmin(iper,:), Sistema, iper, Agrint, ...
          numAgrint);
%---> Cálculo das sobras 
      for isis = 1:nsis
         Sobra(isis,iper,isim) = round(max(0, ...
            (GHmax(iper,isis,isim) + GTmax(iper,isis) + DispNS(isis,iper)) + ...
               squeeze(sum(Interc(:,isis,iper,isim))) - ...
            (Mercado(isis,iper) + squeeze(sum(Interc(isis,:,iper,isim))))));
      end

      fprintf('\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b');
   end
end
fprintf('   OK\n');
